[package]
name = "moving_average"
version = "0.1.0"
edition = "2018"

[dependencies]
num-traits = "0.2.14"

[dev-dependencies]
rand = { version = "0.8.4", features = ["small_rng"] }
nalgebra = "0.29.0"
euclid = "0.22.6"
cgmath = "0.18.0"
